version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: '../../'
      dockerfile: .docker/Dockerfile
    ports:
      - 8000:8080
    volumes:
      - ../../app:/var/www/html:delegated
      - ./start.sh:/start.sh:ro
